install:
	- yes | sudo apt-add-repository ppa:texlive-backports/ppa
	- sudo apt-get update -qq
	- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 

script:
	- make